version: '3.5'

services:
  backend:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./src:/src
      - ./entrypoint.sh:/entrypoint.sh
    # command: "sleep 500"

    entrypoint:
      - /entrypoint.sh

